import { create } from 'zustand';
import { devtools } from 'zustand/middleware';

export const MODAL_KEY = {
	OFF: 'OFF',
	ON_LEAVE_MEMBER_CONFIRM_MODAL: 'ON_LEAVE_MEMBER_CONFIRM_MODAL',
	ON_LEAVE_MEMBER_SUCCESS_MODAL: 'ON_LEAVE_MEMBER_SUCCESS_MODAL',
	ON_STORE_EDIT_COMPLETION_CONFIRM_MODAL: 'ON_STORE_EDIT_COMPLETION_CONFIRM_MODAL',
	ON_STORE_EDIT_SUCCESS_MODAL: 'ON_STORE_EDIT_SUCCESS_MODAL',
	ON_STORE_PRODUCT_EDIT_EXIT_CONFIRM_MODAL: 'ON_STORE_PRODUCT_EDIT_EXIT_CONFIRM_MODAL',
	ON_STORE_PRODUCT_EDIT_SUCCESS_MODAL: 'ON_STORE_PRODUCT_EDIT_SUCCESS_MODAL',
	ON_STORE_PRODUCT_REQUIRED_WARNING_MODAL: 'ON_STORE_PRODUCT_REQUIRED_WARNING_MODAL',
	ON_STORE_REGISTRATION_CANCEL_CONFIRM_MODAL: 'ON_STORE_REGISTRATION_CANCEL_CONFIRM_MODAL',
	ON_STORE_REGISTRATION_CANCEL_SUCCESS_MODAL: 'ON_STORE_REGISTRATION_CANCEL_SUCCESS_MODAL',
	ON_STORE_REGISTRATION_CONFIRM_MODAL: 'ON_STORE_REGISTRATION_CONFIRM_MODAL',
	ON_STORE_REGISTRATION_EXIT_CONFIRM_MODAL: 'ON_STORE_REGISTRATION_EXIT_CONFIRM_MODAL',
	ON_STORE_REGISTRATION_STEP_CHANGE_CONFIRM_MODAL: 'ON_STORE_REGISTRATION_STEP_CHANGE_CONFIRM_MODAL',
} as const;

export type ModalStore = {
	modalKey: string;
	changeModalKey: (changedModalKey: string) => void;
};

export type InitialState = { modalKey: string };
export type setModal = { changeModal: (changedModalKey: string) => void };

export const modalStore = (set) => ({
	modalKey: MODAL_KEY.OFF,
	changeModalKey: (changedModalKey: string) => set(() => ({ modalKey: changedModalKey })),
});

const useModalStore = create<ModalStore>()(process.env.NODE_ENV === 'production' ? modalStore : devtools(modalStore));

export default useModalStore;
